### ISSUE TITLE
Script stuck on input parameters

### ISSUE THREAD

**Issue by peralmq** [aws/elastic-load-balancing-tools#4]
I cannot get the script to work. 

First it had an unstated dependency (that I was able to resolve). You need to `pip install boto3`.

But then it won't accept my input this is what's happening:
```
> ./copy_classic_load_balancer.py --name=lor-backend-LB -region=eu-east-1 --dry-run
usage: copy_classic_load_balancer.py --elb-name <elb name> --region
copy_classic_load_balancer.py: error: argument --region is required

```

PS. There's a typo on https://github.com/aws/elastic-load-balancing-tools/blob/54f6d75dfd9af0922591c2aea263f322c65420c6/copy_classic_load_balancer.py#L397 s/elb-name/name

**Comment by coltoncat** [comment]
Yes, currently there is no error handling to identify a missing boto3 dependency (or an earlier version). 

What I do see is that your command line in the sample you have pasted, does not have two hyphens in front of the "region" parameter. It should be:

`> ./copy_classic_load_balancer.py --name=lor-backend-LB --region=eu-east-1 --dry-run`

i.e., you need to have "--region" rather than "-region"

Good catch on the typo in the line - fixing that...

**Comment by coltoncat** [comment]
Commit fixes the typo...
